language: android
jdk: oraclejdk7
sudo: false

before_script:
  - wget https://services.gradle.org/distributions/gradle-2.12-bin.zip
  - unzip gradle-2.12-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.12
  - export PATH=$GRADLE_HOME/bin:$PATH

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

script: gradle build
